spring:
  profiles:
    active: develop
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rooglexie-girl
    username: root
    password: 950505
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    ehcache:
      config: ehcache.xml
  output:
    ansi:
      enabled: detect
management:
  port: 55555
  health:
    mail:
      enabled: true
  info:
    git:
      mode: full
logging:
  config: classpath:logback-spring.xml
